# Generated by Django 5.1.5 on 2025-01-16 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=100)),
                ("telephone", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Fournisseur",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=100)),
                ("telephone", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Medicament",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=100)),
                ("quantite_stock", models.IntegerField()),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.fournisseur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Commande",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date_commande", models.DateField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.client",
                    ),
                ),
                (
                    "medicament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.medicament",
                    ),
                ),
            ],
        ),
    ]
