# Generated by Django 5.2.6 on 2025-11-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="commande",
            name="quantite",
            field=models.IntegerField(default=1),
        ),
    ]
