# Generated by Django 5.2.6 on 2025-12-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_commande_quantite"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="adresse",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
