# Generated by Django 5.2.6 on 2025-12-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_client_adresse"),
    ]

    operations = [
        migrations.CreateModel(
            name="Livreur",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=100)),
                ("telephone", models.CharField(max_length=15)),
            ],
        ),
    ]
