# Generated by Django 5.2.6 on 2025-12-27 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_livreur"),
    ]

    operations = [
        migrations.AddField(
            model_name="commande",
            name="livreur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="listings.livreur",
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="statut",
            field=models.CharField(
                choices=[
                    ("en_cours", "En cours"),
                    ("livree", "Livrée"),
                    ("annulee", "Annulée"),
                ],
                default="en_cours",
                max_length=20,
            ),
        ),
    ]
