# Generated by Django 5.2.6 on 2026-01-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_client_user_alter_client_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="ville",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="client",
            name="telephone",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
